mode: auto

# å¤´åƒ
avatar:
  url: /images/LastEmbryo.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

# æ ‡ç­¾äº‘
wordcloud:
  enable: true
  height: 650

# æœç´¢
engine_search:
  enable: false

local_search:
  enable: true

# æ–‡ç« ä¿¡æ¯
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# å¥³å­©ä»¬
girls:
  enable: true

# ç‰¹æ®Šé¡µé¢
pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink
  - name: æˆ‘çš„ç›¸å†Œ
    url: /albums/
    icon: icon-train-line
    color: Aqua 

# ç›¸å†Œ
albums:
  enable: true

# pjax
pjax:
  enable: true

# æ–‡ç« åˆ†ç±»é“¾æ¥-ç‚¹å‡»æ ‡é¢˜è·³è½¬é“¾æ¥
types:
  link:
    color: blue
    icon: icon-external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: icon-bilibili-line
  douban:
    color: "#007722"
    icon: icon-douban-line
  github:
    color: black
    icon: icon-github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: icon-netease-cloud-music-line
  notion:
    color: black
    icon: icon-notion
  twitter:
    color: "#1da1f2"
    icon: icon-twitter-line
  zhihu:
    color: "#0084FF"
    icon: icon-zhihu-line


# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

# CDN
cdn:
  pre: https://cdn.jsdelivr.net/gh/chenjing185/chenjing185.github.io@latest


# é¦–é¡µæ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: ç®±ä¸­ä¸–ç•ŒHakoniwa
  border: true
  cloud:
    enable: true
    color: "blue"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# è¯„è®º
comment:
  enable: true
  candidates:
    - github_issues
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿ç§»æ­¥Github issuesä¸æˆ‘äº¤æµã€‚

github_issues:
  enable: true
  username: chenjing185
  repository: chenjing185.github.io
  filters: is:issue

# åˆ†æç»Ÿè®¡
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

# é¼ æ ‡æ•ˆæœ
cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

# èµèµ
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: å¦‚æœè¿™ç¯‡æ–‡ç« å¯¹æ‚¨æœ‰æ‰€å¸®åŠ©çš„è¯,å¸Œæœ›æ‚¨èƒ½è¯·ä½œè€…å–æ¯å’–å•¡
  methods:
    - name: æ”¯ä»˜å®
      path: /images/zfb.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /images/wx.png
      color: "#2DC100"
      icon: icon-wechat-pay-line

tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  è½»å°è¯´: saddlebrown
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: "#0078e7"
  éšç¬”: mediumpurple
  Linux: "#2577b1"

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true

# æ–‡ç« ç›®å½•
toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: true

# åˆ†äº«ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

# é¡µé¢å°¾éƒ¨
footer:
  since: 2022
  icon:
    url: https://sponsors.yunyoujun.cn
    title: é©°éª‹ç®±åº­ä¸­çš„è‹±æ°ä»¬
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-03-20T00:00:00"
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ

# å·¦ä¾§é“¾æ¥
social:
  - name: QQ 1050458482
    link: http://wpa.qq.com/msgrd?v=3&uin=2634687521&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/chenjing185
    icon: icon-github-line
    color: "#6e5494"
  - name: è±†ç“£
    link: https://www.douban.com/people/187322196
    icon: icon-douban-line
    color: "#007722"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=380939349
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/zui-ai-shi-shen-tian-xia
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/39080563
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Twitter
    link: https://twitter.com/home
    icon: icon-twitter-line
    color: "#1da1f2"
  - name: E-Mail
    link: mailto:adf13148320@163.com
    icon: icon-mail-line
    color: "#8E71C1"